### ISSUE TITLE
App crash after adding symbol

### ISSUE THREAD

**Issue by aedahh** [theBoyMo/market-data-tracker#2]
Hello, thank you for sharing this project source.
After adding a symbol, the app crash with log below. 
Now every time the app is launched, it crash.
Is this source still working for anyone?

10-25 17:30:59.441 3151-3151/com.example.marketdatatracker I/StockSelectorFragment:188: updating adapter: com.example.marketdatatracker.ui.fragments.StockSelectorFragment$StockSymbolAdapter@a50707b8
10-25 17:31:46.441 3151-3233/com.example.marketdatatracker E/AndroidRuntime: FATAL EXCEPTION: Thread-141
    Process: com.example.marketdatatracker, PID: 3151
    java.lang.StringIndexOutOfBoundsException: length=8; regionStart=0; regionLength=-1
        at java.lang.String.startEndAndLength(String.java:588)
        at java.lang.String.substring(String.java:1475)
        at yahoofinance.quotes.stock.StockQuotesRequest.parseCSVLine(StockQuotesRequest.java:123)
        at yahoofinance.quotes.stock.StockQuotesRequest.parseCSVLine(StockQuotesRequest.java:11)
        at yahoofinance.quotes.QuotesRequest.getResult(QuotesRequest.java:93)
        at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:349)
        at yahoofinance.YahooFinance.get(YahooFinance.java:201)
        at yahoofinance.YahooFinance.get(YahooFinance.java:180)
        at com.example.marketdatatracker.network.GetStockQuoteThread.run(GetStockQuoteThread.java:73)
10-25 17:31:57.051 3251-3265/com.example.marketdatatracker E/AndroidRuntime: FATAL EXCEPTION: Thread-133
    Process: com.example.marketdatatracker, PID: 3251
    java.lang.StringIndexOutOfBoundsException: length=8; regionStart=0; regionLength=-1
        at java.lang.String.startEndAndLength(String.java:588)
        at java.lang.String.substring(String.java:1475)
        at yahoofinance.quotes.stock.StockQuotesRequest.parseCSVLine(StockQuotesRequest.java:123)
        at yahoofinance.quotes.stock.StockQuotesRequest.parseCSVLine(StockQuotesRequest.java:11)
        at yahoofinance.quotes.QuotesRequest.getResult(QuotesRequest.java:93)
        at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:349)
        at yahoofinance.YahooFinance.get(YahooFinance.java:201)
        at yahoofinance.YahooFinance.get(YahooFinance.java:180)
        at com.example.marketdatatracker.network.GetStockQuoteThread.run(GetStockQuoteThread.java:73)

**Comment by TheBoyMoe** [comment]
Hi Aedahh
I'm glad you found the app to be of use, but I'm not actively supporting it.
It's been 3 years since I looked at it, and I've not used java since.
Sorry I can't be of more help

Bill

**Comment by aedahh** [comment]
Thanks Bill

If anyone else is looking at this, you will need to update the Yahoo Finance API library and possible code to parse new response.
The master source is using Yahoo Finance API version 2.0.0, it is now 3.14.0 and the response is not longer same, causing parsing error.
